name: police-daily-update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # Runs every day at 08:00 UTC

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python pipelines
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          # 1. Update features with new data
          python src/1_daily_feature_pipeline.py
          
          # 2. Retrain the model with the latest data
          # python src/2_training_pipeline.py
          
          # 3. Generate new predictions and charts
          python src/3_inference_pipeline.py

      - name: github pages publish
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Police Crime Dashboard updated"
          commit_options: '--no-verify --signoff'
          
          # This saves the generated image back to your repository
          file_pattern: 'crime_forecast.png'
          
          repository: .
          status_options: '--untracked-files=no'
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
          push_options: '--force'